Bugfix: run checkTooling before using tools

diff --git a/check_ssd b/check_ssd
--- a/check_ssd
+++ b/check_ssd
@@ -21,20 +21,22 @@
 # script to work properly.
 #
 # ChangeLog:
-# Version	Change
-# 1.0		Initial release
-# 1.1		Support for multiple LSI controllers
-# 1.2		Correctly identify which blockdevice (/dev/sdX) belongs to which controller
-# 1.3		Replace lsblk -S with lsscsi. -S flag on lsblk is not available on Wheezy
-# 1.4		Add support for NVMe disks
+# Version       Change
+# 1.0           Initial release
+# 1.1           Support for multiple LSI controllers
+# 1.2           Correctly identify which blockdevice (/dev/sdX) belongs to which controller
+# 1.3           Replace lsblk -S with lsscsi. -S flag on lsblk is not available on Wheezy
+# 1.4           Add support for NVMe disks
+# 1.5           Bugfix: Actually run checkTooling before using the tools that needs checking
 
-VERSION="1.4"
+VERSION="1.5"
 
 STORCLI="/usr/bin/storcli"
 TWARE="/usr/bin/tw_cli"
 BC="/usr/bin/bc"
 SMARTCTL="/usr/sbin/smartctl"
 NVMECLI="/usr/sbin/nvme"
+LSBLK="/bin/lsblk"
 
 MESSAGE=""
 EXITCODE=0  
@@ -101,21 +103,24 @@ esac
 done
 # End parsing parameters
 
-if [ -z ${CARD+X} ]; then 
-  # Check for local devices
-  LOCAL_SSD=`/bin/lsblk -d -o name,rota | /usr/bin/awk '$2 == 0' | wc -l`
-  if [ $LOCAL_SSD -gt 0 ];
-  then
-    CONTROLLER="auto"
-  else 
-    CONTROLLER=`lspci | grep RAID`
+function searchController {
+  if [ -z ${CARD+X} ]; then 
+    # Check for local devices
+    LOCAL_SSD=`$LSBLK -d -o name,rota | /usr/bin/awk '$2 == 0' | wc -l`
+    if [ $LOCAL_SSD -gt 0 ];
+    then
+      CONTROLLER="auto"
+    else 
+      CONTROLLER=`lspci | grep RAID`
+    fi
+  else
+    CONTROLLER=${CARD,,} #,, means lowercase
   fi
-else
-  CONTROLLER=${CARD,,} #,, means lowercase
-fi
-
+}
 
 function checkTooling {
+  if [ ! -f $LSBLK ]; then echo "UNKNOWN: lsblk not found"; exit 4; fi
+
   case ${CONTROLLER,,} in
     *lsi*)
       if [ ! -f $STORCLI ]; then echo "UNKNOWN: storcli tool not found"; exit 4; fi
@@ -126,7 +131,7 @@ function checkTooling {
   esac
 
   # Only check for nvme-cli if we have nvme-cli
-  LOCAL_NVME=`/bin/lsblk -d -o name,rota | /usr/bin/awk '$2 == 0' | grep nvme | wc -l`
+  LOCAL_NVME=`$LSBLK -d -o name,rota | /usr/bin/awk '$2 == 0' | grep nvme | wc -l`
   if [ $LOCAL_NVME -gt 0 ];
   then
     if [ ! -f $NVMECLI ]; then echo "UNKNOWN: nvme-cli not found"; exit 4; fi
@@ -144,12 +149,12 @@ function getDIDlist {
       ITERATE=0
       for c in `storcli show | egrep "^  [0-9]" | awk '{ print $1 }'`; do
         CONTROLLERS[$ITERATE]=$c
-#        BLOCKDEVICE[$ITERATE]=`/bin/lsblk -d -S -n --output HCTL,NAME | sed "s/:/ /g" | awk '{ print \$1 " " \$5 }' | grep ^$c | tail --lines 1 | awk '{ print "/dev/" $2 }'`
+#        BLOCKDEVICE[$ITERATE]=`$LSBLK -d -S -n --output HCTL,NAME | sed "s/:/ /g" | awk '{ print \$1 " " \$5 }' | grep ^$c | tail --lines 1 | awk '{ print "/dev/" $2 }'`
         BLOCKDEVICE[$ITERATE]=`lsscsi | sed "s/\[//g; s/\]//g" | awk '{ print $1 " " $6 }' | sed "s/:/ /g" | awk '{ print \$1 " " \$5 }' | grep ^$c | tail --lines 1 | awk '{ print $2 }'`
         DIDLIST[$ITERATE]=`$STORCLI /c$ITERATE show | grep SSD | awk '{ print $2 }'`
         if [ $DEBUG -eq 1 ]; then echo "Found controller #${CONTROLLERS[$ITERATE]} with associated blockdevice ${BLOCKDEVICE[$ITERATE]}"; fi;
 
-	ITERATE=$((ITERATE + 1))
+        ITERATE=$((ITERATE + 1))
       done
     ;;
     *3ware*)
@@ -166,8 +171,8 @@ function getDIDlist {
       DRIVER="auto"
 
       CONTROLLERS[0]=0
-      BLOCKDEVICE[0]=`/bin/lsblk -d -o name,rota | grep "$DEVICE" | /usr/bin/awk '$2 == 0 { print "/dev/"$1 }'`
-      DIDLIST[0]=`/bin/lsblk -d -o name,rota | grep "$DEVICE" | /usr/bin/awk '$2 == 0 { print "/dev/"$1 }'`
+      BLOCKDEVICE[0]=`$LSBLK -d -o name,rota | grep "$DEVICE" | /usr/bin/awk '$2 == 0 { print "/dev/"$1 }'`
+      DIDLIST[0]=`$LSBLK -d -o name,rota | grep "$DEVICE" | /usr/bin/awk '$2 == 0 { print "/dev/"$1 }'`
     ;;
     *)
       echo "UNKNOWN: Unknown controller or no controller found"
@@ -205,11 +210,11 @@ function checkDID () {
   do
       if [ $DEBUG -eq 1 ]; then echo "Checking DID number $d on controller $1 with driver $DRIVER"; fi
       if [ "$DRIVER" = "auto" ]; then
-	if [[ $d =~ ^/dev/nvme.* ]]; then
-		VALUE=`echo \`$NVMECLI smart-log-add $d | grep "^wear_leveling" | tr -d '%' | awk '{ print $3 }'\` + 0 | bc`
-	else
-        	VALUE=`echo \`$SMARTCTL -A -d auto $d | grep "^177\|^233" | awk '{ print $4 }'\` + 0 | bc`  
-	fi
+        if [[ $d =~ ^/dev/nvme.* ]]; then
+                VALUE=`echo \`$NVMECLI smart-log-add $d | grep "^wear_leveling" | tr -d '%' | awk '{ print $3 }'\` + 0 | bc`
+        else
+                VALUE=`echo \`$SMARTCTL -A -d auto $d | grep "^177\|^233" | awk '{ print $4 }'\` + 0 | bc`  
+        fi
       else
         VALUE=`echo \`$SMARTCTL -A -d $DRIVER,$d ${BLOCKDEVICE[$1]} | grep "^177\|^233" | awk '{ print $4 }'\` + 0 | bc`  
       fi
@@ -257,7 +262,8 @@ function checkSSDs {
 
 
 checkTooling # must run as first
-getDIDlist # Must run second
+searchController
+getDIDlist
 hasSSDs
 
 if [ $TESTMODE -eq 1 ];
